// Data Film & Serial IDLIX
// Semua gambar menggunakan gambar sinematik resolusi tinggi dan video menggunakan stream MP4 publik berkualitas tinggi

const MOVIES_DATA = [
  {
    id: "film-1",
    title: "Cyber City 2099",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    synopsis: "Di masa depan di mana kecerdasan buatan mengendalikan distrik metropolitan New Neo, seorang detektif sibernetik menemukan konspirasi di balik hilangnya kesadaran manusia murni terakhir.",
    match: "98%",
    ageRating: "18+",
    year: "2024",
    duration: "2j 14m",
    quality: "4K Ultra HD",
    categories: ["trending", "scifi", "action"],
    genres: ["Fiksi Ilmiah", "Aksi", "Cyberpunk", "Distopia"],
    cast: ["Kenji Sato", "Elena Rostova", "Marcus Vance"],
    director: "Ridley Scott",
    isFeatured: true
  },
  {
    id: "film-2",
    title: "Shadow Hunter: Kebangkitan",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    synopsis: "Ketika gerbang kegelapan terbuka di tengah hutan belantara Nusantara, seorang pemburu bayangan kuno harus memilih antara membalaskan dendam masa lalu atau menyelamatkan peradaban.",
    match: "95%",
    ageRating: "16+",
    year: "2024",
    duration: "1j 52m",
    quality: "HD",
    categories: ["trending", "action", "top10"],
    genres: ["Aksi", "Fantasi Gelap", "Petualangan"],
    cast: ["Iko Kurniawan", "Tara Basro", "Joe Taslim"],
    director: "Timo Tjahjanto"
  },
  {
    id: "film-3",
    title: "The Silent Cosmos",
    type: "series",
    backdrop: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    synopsis: "Sebuah sinyal misterius dari luar galaksi Bima Sakti diterima oleh stasiun penelitian terpencil. Kru astronot harus memutuskan apakah akan membalas atau mematikan seluruh pemancar sebelum terlambat.",
    match: "97%",
    ageRating: "13+",
    year: "2023",
    duration: "2 Musim",
    quality: "4K Ultra HD",
    categories: ["trending", "scifi", "top10"],
    genres: ["Fiksi Ilmiah", "Misteri", "Drama Luar Angkasa"],
    cast: ["Jessica Miller", "David Oyelowo", "Hiroyuki Sanada"],
    director: "Christopher Nolan"
  },
  {
    id: "film-4",
    title: "Misteri Rumah Tua Kaliurang",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    synopsis: "Sekelompok mahasiswa arsitektur menjelajahi vila peninggalan zaman kolonial di lereng Gunung Merapi. Mereka tidak menyadari bahwa vila tersebut dibangun di atas ritual perjanjian kuno.",
    match: "91%",
    ageRating: "18+",
    year: "2024",
    duration: "1j 48m",
    quality: "HD",
    categories: ["horror", "top10"],
    genres: ["Horor", "Misteri", "Thriller"],
    cast: ["Chelsea Islan", "Reza Rahadian", "Laura Basuki"],
    director: "Joko Anwar"
  },
  {
    id: "film-5",
    title: "Tokyo Midnight Drift",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    synopsis: "Kecepatan tinggi, lampu neon, dan taruhan tanpa batas. Di jalan tol Shuto Expressway, para pembalap jalanan bawah tanah bertarung untuk supremasi dan kebebasan dari sindikat Yakuza.",
    match: "93%",
    ageRating: "16+",
    year: "2023",
    duration: "2j 05m",
    quality: "4K Ultra HD",
    categories: ["action", "trending"],
    genres: ["Aksi", "Balapan", "Kriminal"],
    cast: ["Takeru Satoh", "Sung Kang", "Nana Komatsu"],
    director: "Justin Lin"
  },
  {
    id: "film-6",
    title: "Detektif Batavia: Berkas Merah",
    type: "series",
    backdrop: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    synopsis: "Tahun 1928 di Batavia. Seorang detektif pribumi yang cerdas bekerja sama dengan jurnalis wanita untuk memecahkan rangkaian pembunuhan berantai yang mengancam stabilitas pemerintah Hindia.",
    match: "96%",
    ageRating: "16+",
    year: "2024",
    duration: "1 Musim (8 Ep)",
    quality: "HD",
    categories: ["drama", "top10", "trending"],
    genres: ["Drama", "Kriminal", "Sejarah", "Misteri"],
    cast: ["Ario Bayu", "Putri Marino", "Lukman Sardi"],
    director: "Garin Nugroho"
  },
  {
    id: "film-7",
    title: "Kingdom of Seoul: Dinasti Zombie",
    type: "series",
    backdrop: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    synopsis: "Saat wabah misterius mengubah orang mati menjadi monster ganas di era Joseon, putra mahkota yang diasingkan harus memimpin perlawanan putus asa demi menyelamatkan rakyatnya.",
    match: "99%",
    ageRating: "18+",
    year: "2023",
    duration: "3 Musim",
    quality: "4K Ultra HD",
    categories: ["trending", "horror", "action", "top10"],
    genres: ["K-Drama", "Aksi", "Horor Zombie", "Sejarah"],
    cast: ["Ju Ji-hoon", "Bae Doona", "Ryu Seung-ryong"],
    director: "Kim Seong-hun"
  },
  {
    id: "film-8",
    title: "Petualangan Si Kelinci Ajaib",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    synopsis: "Kisah animasi hangat tentang kelinci raksasa berhati lembut di padang rumput yang harus melindungi teman-teman kecilnya dari gangguan tupai-tupai nakal hutan pinus.",
    match: "94%",
    ageRating: "Semua Umur",
    year: "2024",
    duration: "1j 30m",
    quality: "HD",
    categories: ["animation", "trending"],
    genres: ["Animasi", "Keluarga", "Komedi", "Petualangan"],
    cast: ["Sacha Goedegebure", "Jan Morgenstern"],
    director: "Blender Animation Studio"
  },
  {
    id: "film-9",
    title: "The Neon Syndicate",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    synopsis: "Perang pengaruh antar geng kriminal di kota masa depan yang disinari neon. Saat sang bos mafia tewas, perebutan kekuasaan berdarah tak dapat dihindari.",
    match: "92%",
    ageRating: "18+",
    year: "2023",
    duration: "2j 10m",
    quality: "4K Ultra HD",
    categories: ["action", "drama"],
    genres: ["Aksi", "Neo-Noir", "Kriminal"],
    cast: ["Mads Mikkelsen", "Ana de Armas", "Karl Urban"],
    director: "Chad Stahelski"
  },
  {
    id: "film-10",
    title: "Keluarga Cemara Harapan",
    type: "series",
    backdrop: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    synopsis: "Sebuah keluarga sederhana di pedesaan Jawa Tengah menghadapi berbagai lika-liku kehidupan, pendidikan anak-anak, dan kehangatan gotong royong warga desa.",
    match: "98%",
    ageRating: "13+",
    year: "2024",
    duration: "2 Musim",
    quality: "HD",
    categories: ["drama"],
    genres: ["Drama", "Keluarga", "Inspiratif"],
    cast: ["Ringgo Agus Rahman", "Nirina Zubir", "Zara Adhisty"],
    director: "Yandy Laurens"
  },
  {
    id: "film-11",
    title: "Black Hole Paradox",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    synopsis: "Sebuah ekspedisi ilmiah mendekati lubang hitam supermasif untuk menyelidiki anomali waktu. Namun semakin dekat mereka, semakin kenyataan terpecah menjadi dimensi jamak.",
    match: "97%",
    ageRating: "13+",
    year: "2024",
    duration: "2j 28m",
    quality: "4K Ultra HD",
    categories: ["scifi", "trending"],
    genres: ["Fiksi Ilmiah", "Petualangan", "Misteri"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Michael Caine"],
    director: "Christopher Nolan"
  },
  {
    id: "film-12",
    title: "Kutukan Malam Jumat Kliwon",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    synopsis: "Setiap siklus 50 tahun sekali pada Malam Jumat Kliwon, gerbang pemakaman keramat desa Alas Tua terbuka dan memburu keturunan dari pelaku pesugihan masa lampau.",
    match: "90%",
    ageRating: "18+",
    year: "2023",
    duration: "1j 42m",
    quality: "HD",
    categories: ["horror"],
    genres: ["Horor", "Mitos Nusantara", "Mencekam"],
    cast: ["Luna Maya", "Christian Sugiono", "Sara Wijayanto"],
    director: "Rocky Soraya"
  },
  {
    id: "film-13",
    title: "Laugh Factory Jakarta: Stand Up Special",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    synopsis: "Komika papan atas Indonesia berkumpul dalam satu panggung untuk menertawakan realitas kehidupan metropolitan, asmara, dan dinamika budaya kantor modern.",
    match: "94%",
    ageRating: "16+",
    year: "2024",
    duration: "1j 25m",
    quality: "HD",
    categories: ["animation", "drama"],
    genres: ["Komedi", "Stand Up", "Hiburan"],
    cast: ["Raditya Dika", "Ernest Prakasa", "Pandji Pragiwaksono"],
    director: "Ernest Prakasa"
  },
  {
    id: "film-14",
    title: "Operasi Kraken: Perang Bawah Laut",
    type: "movie",
    backdrop: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80",
    poster: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    synopsis: "Di palung laut terdalam samudera Pasifik, kapal selam tempur siluman terjebak dalam krisis nuklir dan berhadapan dengan fenomena organisme purba tak dikenal.",
    match: "91%",
    ageRating: "16+",
    year: "2024",
    duration: "2j 01m",
    quality: "4K Ultra HD",
    categories: ["action", "scifi"],
    genres: ["Aksi", "Thriller Militer", "Petualangan"],
    cast: ["Gerard Butler", "Gary Oldman", "Common"],
    director: "Donovan Marsh"
  }
];

// Kategori baris untuk tampilan Netflix
const CATEGORIES = [
  { id: "trending", title: "🔥 Sedang Tren Sekarang", filter: (m) => m.categories.includes("trending") },
  { id: "top10", title: "⭐ 10 Film & Acara Teratas di Indonesia Hari Ini", filter: (m) => m.categories.includes("top10") || parseInt(m.match) > 95 },
  { id: "action", title: "💥 Film Laga & Petualangan Penuh Aksi", filter: (m) => m.categories.includes("action") || m.genres.includes("Aksi") },
  { id: "scifi", title: "🚀 Fiksi Ilmiah & Fenomena Luar Angkasa", filter: (m) => m.categories.includes("scifi") || m.genres.includes("Fiksi Ilmiah") },
  { id: "horror", title: "👻 Horor & Misteri Menegangkan", filter: (m) => m.categories.includes("horror") || m.genres.includes("Horor") },
  { id: "drama", title: "🎭 Drama & Kisah Emosional Menggugah", filter: (m) => m.categories.includes("drama") || m.genres.includes("Drama") }
];
